# Generated by Django 4.0.4 on 2022-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cover', models.ImageField(upload_to='')),
                ('book_name', models.CharField(max_length=100)),
                ('book_subtitle', models.CharField(max_length=100)),
                ('book_description', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Card Books',
                'verbose_name_plural': 'Card Books',
            },
        ),
    ]
