# Generated by Django 4.0.4 on 2022-05-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcardsmodel',
            name='full_description',
            field=models.TextField(default=1, max_length=700),
            preserve_default=False,
        ),
    ]
