# Generated by Django 4.0.4 on 2022-05-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='searchfunc.agent')),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchfunc.profile')),
            ],
            options={
                'verbose_name': 'Users Online',
                'verbose_name_plural': 'Users Model',
            },
        ),
    ]
