# Generated by Django 4.0.4 on 2022-05-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0002_bookcardsmodel_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcardsmodel',
            name='shop_details_description',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
