# Generated by Django 4.0.4 on 2022-05-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0002_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_organised',
            field=models.BooleanField(default=False),
        ),
    ]
