# Generated by Django 4.0.4 on 2022-05-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0003_alter_user_is_organised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimagescontent',
            name='slider_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
