# Generated by Django 4.0.4 on 2022-05-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0003_bookcardsmodel_shop_details_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcardsmodel',
            name='shop_cost',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
