# Generated by Django 4.0.4 on 2022-05-02 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0004_bookcardsmodel_shop_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name': 'Book Category',
                'verbose_name_plural': 'Book Category',
            },
        ),
        migrations.AddField(
            model_name='bookcardsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='searchfunc.bookcategorymodel'),
        ),
    ]
