# Generated by Django 4.0.4 on 2022-05-07 05:54

from django.db import migrations, models
import searchfunc.validators


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0009_essentialspagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialspagemodel',
            name='essential_page_image',
            field=models.FileField(upload_to='', validators=[searchfunc.validators.validate_file_extension]),
        ),
    ]
