# Generated by Django 4.0.4 on 2022-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0010_alter_essentialspagemodel_essential_page_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialRightContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essential_right_image', models.ImageField(upload_to='')),
                ('essentials_right_content', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Essential Right',
                'verbose_name_plural': 'Essential Right',
            },
        ),
    ]
