# Generated by Django 4.0.4 on 2022-05-09 18:00

from django.db import migrations, models
import searchfunc.validators


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0011_essentialrightcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_img', models.FileField(upload_to='', validators=[searchfunc.validators.validate_file_extension])),
                ('count_number', models.IntegerField()),
                ('count_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Count Page',
                'verbose_name_plural': 'Count Page',
            },
        ),
    ]
