# Generated by Django 4.0.4 on 2022-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0012_countpagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksToRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_subititle', models.CharField(max_length=70)),
                ('book_cover_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Book to read',
                'verbose_name_plural': 'Books to read',
            },
        ),
    ]
