# Generated by Django 4.0.4 on 2022-05-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchfunc', '0013_bookstoread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMePartContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_header', models.CharField(max_length=60)),
                ('contact_text', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Contact me Context',
            },
        ),
    ]
